### ISSUE TITLE
你好，作者。有电子版的购买途径吗？

### ISSUE THREAD

**Issue by plain-dev** [enbandari/DiveIntoKotlinCoroutines-Sources#1]

**Comment by enbandari** [comment]
京东读书微信读书kindle都有的

--------------原始邮件--------------
发件人："Plain "<notifications@github.com&gt;;
发送时间：2020年7月7日(星期二) 晚上10:07
收件人："enbandari/DiveIntoKotlinCoroutines-Sources" <DiveIntoKotlinCoroutines-Sources@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[enbandari/DiveIntoKotlinCoroutines-Sources] 你好，作者。有电子版的购买途径吗？ (#1)
-----------------------------------

**Comment by plain-dev** [comment]
@enbandari 好的，谢谢
