### ISSUE TITLE
求教sleep

### ISSUE THREAD

**Issue by Palardin3** [enbandari/DiveIntoKotlinCoroutines-Sources#2]
```
 @JvmStatic
    fun main(args: Array<String>) = runBlocking {

        val result = listOf(1, 2, 3, 4).map {
            flow {

                emit(deal(it, System.currentTimeMillis()).also {
                    println("emit " + it + "   耗时" + (System.currentTimeMillis() - it))
                })
            }.flowOn(Dispatchers.IO)
        }.merge().buffer(4)

        result.first().also {
            println("collect " + Thread.currentThread().name)
            println("collect result" + "   " + (System.currentTimeMillis() - it))
        }


        println("end")
    }

    fun deal(value: Int, time: Long): Long {
        println("FLOW " + Thread.currentThread().name)
        sleep(value * 1000L)
        return time
    }
```
结果是等四个全部发送完才能接收到，求教原因。 还有就是QQ群无法添加，感谢

**Comment by enbandari** [comment]
runBlocking 的调度器的问题。换个调度器你就能看到了应该。runBlocking 的调度器是一个类似于 Android Looper 的东西。

--------------原始邮件--------------
发件人："Palardin3 "<notifications@github.com&gt;;
发送时间：2020年7月16日(星期四) 晚上10:02
收件人："enbandari/DiveIntoKotlinCoroutines-Sources" <DiveIntoKotlinCoroutines-Sources@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[enbandari/DiveIntoKotlinCoroutines-Sources] 求教sleep (#2)
-----------------------------------

 

  @JvmStatic     fun main(args: Array<String&gt;) = runBlocking {         val result = listOf(1, 2, 3, 4).map {             flow {                 emit(deal(it, System.currentTimeMillis()).also {                     println("emit " + it + "   耗时" + (System.currentTimeMillis() - it))                 })             }.flowOn(Dispatchers.IO)         }.merge().buffer(4)         result.first().also {             println("collect " + Thread.currentThread().name)             println("collect result" + "   " + (System.currentTimeMillis() - it))         }         println("end")     }     fun deal(value: Int, time: Long): Long {         println("FLOW " + Thread.currentThread().name)         sleep(value * 1000L)         return time     }  
结果是等四个全部发送完才能接收到，求教原因。 还有就是QQ群无法添加，感谢

**Comment by Palardin3** [comment]
可以更详细一点吗，我这边就是在安卓里这样写，发现不太符合预期。不是sleep仅阻塞当前线程吗，我看日志，sleep的并不是main，为何不能接收到发射值

**Comment by enbandari** [comment]
android上不要用runblocking。runblocking会直接在所在线程启动一个循环来做调度，不适合android。详细的你先去看看书了解下细节吧。

--------------原始邮件--------------
发件人："Palardin3 "<notifications@github.com&gt;;
发送时间：2020年7月16日(星期四) 晚上10:18
收件人："enbandari/DiveIntoKotlinCoroutines-Sources" <DiveIntoKotlinCoroutines-Sources@noreply.github.com&gt;;
抄送："Bennyhuo "<bennyhuo@kotliner.cn&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [enbandari/DiveIntoKotlinCoroutines-Sources] 求教sleep (#2)
-----------------------------------

 

 
可以更详细一点吗，我这边就是在安卓里这样写，发现不太符合预期。不是sleep仅阻塞当前线程吗，我看日志，sleep的并不是main，为何不能接收到发射值

**Comment by Palardin3** [comment]
在安卓上没有使用ruanblocking，是用GloableScope.launch

**Comment by enbandari** [comment]
GlobalScope.launch 和 runBlocking 默认的调度器不一样，所以你 sleep 阻塞的线程当然不一样。不要在这个仓库提 issue，QQ 群只要正确回答问题就能加，已经有很多人加进来了。
